# check spelling, codestyle
name: Style and Docstring Check

on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  vale:
    name: Vale
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      # this is equivalent to
      # vale --config doc/.vale.ini doc pyvista examples
      - name: "Run Vale"
        uses: errata-ai/vale-action@reviewdog
        with:
          files: '["doc", "src", "examples"]'
          vale_flags: "--config=doc/.vale.ini"
          reporter: github-pr-check
          level: error
          filter_mode: nofilter
          fail_on_error: true
          version: 2.29.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
