name: PR update

on:
  push:
    branches:
      - "main"
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Automatically update PR
        uses: adRise/update-pr-branch@84354a688583b4a3598345e534e7ad49f98e7330
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "main"
          required_approval_count: 1
          require_passed_checks: false
          sort: "created"
          direction: "desc"
          require_auto_merge_enabled: true
