name: PR update

on:
  push:
    branches:
      - "main"
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: read
      issues: read
    steps:
      - name: Automatically update PR
        uses: adRise/update-pr-branch@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "main"
          required_approval_count: 1
          require_passed_checks: false
          sort: "created"
          direction: "desc"
          require_auto_merge_enabled: true
          # Skip PRs from forks as GITHUB_TOKEN cannot update fork branches
          skip_if_head_is_fork: true
